### ISSUE TITLE
atem audio input state "ext" for tvs missing

### ISSUE THREAD

**Issue by deedos** [CasparCG/client#106]
With 3 days ago version, I could only find options from 1 to 10 input for changing audio inout state. Would be possible to add the "ext" input for ATEM TVS ?
I did confirm with the libqatemcontrol developer (http://www.atemuser.com/forums/atem-vision-mixers/developers/qt-based-lib-connecting-atem-switch)  and he confirmed the options is doable trough his lib.

thanks in advance

**Comment by Julusian** [comment]
ATEM support is being remove in 2.3.0 of this client, so this no longer applies
