### ISSUE TITLE
Client 2.0.7 b3 rundown backward compability

### ISSUE THREAD

**Issue by markusnygard** [CasparCG/Client#117]
If open a rundown made by 2.0.6 in 2.07b3, save it and tries to open it again in 2.0.6 the client crashes.
Error message is "CasparCG has stopped working" from Windows.
Markus Nygård / YLE

**Comment by dotarmin** [comment]
This will be handled more gracefully in the future. Currently the backward compatibility from 2.0.7b3 -> 2.0.6 won't be fixed, unless it's really needed which I can't see for the moment.
