### ISSUE TITLE
CasparCG Client Keys Remapping

### ISSUE THREAD

**Issue by sledzik1984** [CasparCG/client#135]
It wolud be cool to have a feature that allows remapping of keys used in CasparCG Client. With that feature we could use CasparCG client with small wireless presenters such as Logitech R700 (or similar) for starting (or stopping, pausing) clips directly from stage. 

It could be useful on events and conferences when people like to "have control" what is played on screens...

**Comment by Keksstar** [comment]
+1 for that. Some more people asking for this

**Comment by dotarmin** [comment]
This feature request is a duplicate. See issues #104.
