### ISSUE TITLE
Labels and channels change randomly

### ISSUE THREAD

**Issue by mauricev78** [CasparCG/Client#137]
Hi there

we are doing a show where multiple rundowns are open.
next to the labels we change other labels & target change
randomly in other rundown.

**Comment by Zebiolo** [comment]
It's a bug, see issue #134. It's fixed. Please download the latest commit build until next stable (2.0.8) release.

You find commit build here: builds.casparcg.com

**Comment by mauricev78** [comment]
Done that but still labels are changing

so i guess the bug is not fixed
we are now running
2.0.8 
revision f7fb5bbfc

**Comment by mauricev78** [comment]
checking further we found that when there is a red box behind a rundown cue this cue also changes
when editing a other cue.

perhaps this helps in  finding the bug
thanks in front

**Comment by Zebiolo** [comment]
The red box is indicating empty rundown. I can't reproduce any of your problems. Can you describe the steps in more detail?

**Comment by mauricev78** [comment]
I'm not @ a machine now soo i can only tell you
What i experienced last sunday.
Hope  i hope i remeber it Well.

We made our rundowns in the client wich you can download from the site.
We then experienced that labels targets and channels were changing when we changed things in other rundowns.

Then we started to use revision f7fb5bbfc
With the old rundowns since they were quote big.
The problem remains we then noticed that in the same rundowns labels were changing
On rundowns items with the red box.

Normaly the redbox disappears directly  but now it stays.


Grt
Maurice



Maurice Veraart
Head of Video

Creative Technology Holland B.V. | www.ctholland.com
M +31 (0) 651 23 41 75 | T +31 165 581388 | E mveraart@ctholland.com
Twitter<https://twitter.com/CreativeTechnol> | Facebook<http://www.facebook.com/creativetechnologygroup> | Youtube<https://www.youtube.com/user/CTCreativeTechnology>

Rucphensebaan 52, 4706 PJ ROOSENDAAL, Nederland. Please see our Terms and Conditions<http://holland.ct-group.com/legal> of Business. Registered in The Netherlands NL20040032


________________________________________
Van: Zebiolo [notifications@github.com]
Verzonden: woensdag 18 februari 2015 10:04
Aan: CasparCG/Client
CC: Maurice Veraart
Onderwerp: Re: [Client] Labels and channels change randomly (#137)

The red box is indicating empty rundown. I can't reproduce any of your problems. Can you describe the steps in more detail?

**Comment by mauricev78** [comment]
![bug](https://cloud.githubusercontent.com/assets/7240496/6246533/6c61b2d6-b76a-11e4-83af-b1c7cdb31c52.png)

**Comment by mauricev78** [comment]
Testing on a complete different machine
clean install off rev f7fb5bbfc
all rundown with the redbox are changing also in other rundowns
for some reason on this machine the previous selected items do not change.

grt
Maurice

**Comment by Zebiolo** [comment]
Ok, i see the problem. I will fix it, tnx!
