### ISSUE TITLE
Send JSON data when working with Html-templates

### ISSUE THREAD

**Issue by 7omas** [CasparCG/Client#138]
Currently the data sent to an Html-template is xml which has to be parsed.
If that data was instead sent as json it could instantly be inserted and easily accessed in the template.

Current xml:
&lt;templateData&gt;
	&lt;componentData id="f0"&gt;&lt;data id="text" value="f0 data" /&gt;&lt;/componentData&gt;
	&lt;componentData id="f1"&gt;&lt;data id="text" value="f1 data" /&gt;&lt;/componentData&gt;
	&lt;componentData id="f2"&gt;&lt;data id="text" value="f2 data" /&gt;&lt;/componentData&gt;
	&lt;componentData id="f3"&gt;&lt;data id="text" value="f3 data" /&gt;&lt;/componentData&gt;
	&lt;componentData id="f4"&gt;&lt;data id="text" value="f4 data" /&gt;&lt;/componentData&gt;
&lt;/templateData&gt;

Suggested json:
[{
	"f0": "f0 data",
	"f1": "f1 data",
	"f2" : "f2 data",
	"f3" : "f3 data",
	"f4" : "f4 data"
}]

**Comment by 7omas** [comment]
Could be implemented by adding a checkbox above the templateData area saying "send data as JSON"

**Comment by coral** [comment]
+1

**Comment by HellGore** [comment]
It is actually pretty simple to parse the current template-data-xml using XPath:

```javascript
function update(xml) {
    var parser = new DOMParser();
    var document = parser.parseFromString(xml, "text/xml");
    f0 = document.evaluate("/templateData/componentData[@id='f0']/data/@value", document, null, XPathResult.STRING_TYPE, null).stringValue;
    f1 = document.evaluate("/templateData/componentData[@id='f1']/data/@value", document, null, XPathResult.STRING_TYPE, null).stringValue;
    f2 = document.evaluate("/templateData/componentData[@id='f2']/data/@value", document, null, XPathResult.STRING_TYPE, null).stringValue;
    f3 = document.evaluate("/templateData/componentData[@id='f3']/data/@value", document, null, XPathResult.STRING_TYPE, null).stringValue;
    f4 = document.evaluate("/templateData/componentData[@id='f4']/data/@value", document, null, XPathResult.STRING_TYPE, null).stringValue;
}
```

**Comment by 7omas** [comment]
Thanks for implementing it in 2.0.8

However, the implementation does not escape the quotationmarks and so the template doesn't recieve any data.

Current data sent: "[{"f0","value"}]"
Should be: "[{\"f0\",\"value\"}]"

**Comment by jdzPtv** [comment]
Experiencing the same issue as 7omas. We're currently developing HTML templates and want to use JSON as our data format. 
We're using Client 2.0.8 to send data as JSON to Server 2.0.7 Stable, and the server log says it's receiving the data. However, The data is somehow not being forwarded to the template.

Even without parsing the JSON Data, the template isn't receiving anything, which is not the case when sending XML.

Log:
`Received message from 127.0.0.1: CG 1-20 ADD 1 "P/H0.0 - TestJSON/TEMPLATE" 1 "{\"f0\":\"some data\"}"\r\n`

Code:
```
function parseCasparJSON(str) {
    dataCaspar = JSON.parse(str);
}

function update(str) { 
	parseCasparJSON(str); 
	f0 = dataCaspar['f0'];
	$("#f0").text(f0);
}

```
`Uncaught ReferenceError: str is not defined`

**Comment by dotarmin** [comment]
You need to run CasparCG Server 2.1.0.

From client CHANGELOG
> - NEW: Added support for send template data as JSON, issue #138. Requires CasparCG Server 2.1 or later.
