### ISSUE TITLE
Can't choose TRICASTER mixer in the inspector panel

### ISSUE THREAD

**Issue by RTVA** [CasparCG/Client#142]
Here a link where I expose the problem:
http://casparcg.com/forum/viewtopic.php?f=12&t=3038
This seems to be related with this other issue:
https://github.com/CasparCG/Client/issues/132

Hope this help.
Regards,
Michel.

**Comment by Zebiolo** [comment]
Have you tried a recent commit build from builds.casparcg.com?

**Comment by RTVA** [comment]
Hi Zebiolo,

No, What I have to do?

I just downloaded  CasparCG Client ad17d11f4120cdc2f3bfb33fc87464d5d5d60e57.zip  but it seems to be PASS protected...

**Comment by Zebiolo** [comment]
Download and try this one. It´s not password protected:
http://casparcg.com/builds/CasparCG%20Client/master/CasparCG%20Client%20ad17d11f4120cdc2f3bfb33fc87464d5d5d60e57.zip

**Comment by RTVA** [comment]
so, it is :/
Sorry....

**Comment by Zebiolo** [comment]
I have no clue why you get the password dialog. Try install 7-Zip or some other unzip software. I can assure you that there is not password protection.

**Comment by RTVA** [comment]
I've Just downloaded on another PC... No password...SORRY...
I'm going to try...
I will tell you in a few minuts...

**Comment by RTVA** [comment]
SORRY....
I can't open CasparCG Client.exe  (note: I am running Windows XP)
![alert](https://cloud.githubusercontent.com/assets/11145267/6579054/2e8d141c-c748-11e4-8637-b7dfc75f9997.PNG)

**Comment by Zebiolo** [comment]
It should work on WinXP too but i can't verify that. Don't have WinXP here...

**Comment by RTVA** [comment]
OK,
I tried on another PC running Windows 7...
And it's working !!!
Surely I am doing something wrong on the XP... I will check later...

Is this 2.0.8 build usable for production or only for test?

Your program is a gem... Thank you for make it available to all... I just discover it a few days ago, and I am evaluating if it can be interesting on our workflow...  

Congratulation and keep on the good work...

Best regards,
Michel.

**Comment by Zebiolo** [comment]
2.0.8 is quite stable
