### ISSUE TITLE
Problem with slots

### ISSUE THREAD

**Issue by krzyc** [CasparCG/Client#143]
Hi, after removing Q_SLOT macros form soure by https://github.com/CasparCG/Client/commit/4d2185341fd9c5a15b3e316d57ecb1c22dacaa06 Client is not working for me - says there is no slots. After adding slot definitions everything works again.
Am I doing something wrong or this is a bug?
I am using recommended 64-bit Qt environment Qt 5.4.1 64-bit MinGW 4.9.2 SEH.
Are there new requirements for compilation?

**Comment by Zebiolo** [comment]
It's my fault!

I am currently migrating the code to C++11 and Qt new signal and slot system. This one slipped into the repo, sorry.
