### ISSUE TITLE
Failed to build gpi

### ISSUE THREAD

**Issue by dlang9159** [CasparCG/Client#162]
I tried to compile CasparCG Client by myself with QtCreator 3.4.2 using MinGW 5.10 64bit and Qt 5.5.0 running Windows 10 (and also 8).

I ran into following problem:
..\src\Gpi\GpiDevice.cpp:-1 Fehler: undefined reference to `gpio::serial_port_device::create(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, boost::function<void (bool)> const&)'  on line 19

Is this a common problem or is it just me?
If you comment this line out, it builds fine, but the application is unstable because this function is removed.

BTW: http://tver-soft.org/qt64 is offline, the corresponding sourceforge project is closed.

**Comment by Zebiolo** [comment]
Updated readme file with a link to build tools for Windows x64.

**Comment by dlang9159** [comment]
I can't download the files:
"Forbidden - You don't have permission to access /build-tools/qt-creator-3.3.0-x64.exe on this server."
Thanks for that fast reply, I'll try it with this setup as soon as the download is avaible and check if the build error is resolved.

**Comment by hummelstrand** [comment]
Sorry about that, the files are now downloadable!

**Comment by dlang9159** [comment]
Thank you, everything works fine now :)
