### ISSUE TITLE
ATEM STING/DVE BUG

### ISSUE THREAD

**Issue by Streamscape** [CasparCG/Client#173]
When connected to an atem 2m/e 4K chosing tools>ATEM>Trigger Auto>Transitions>Sting actualy switches the DVE for the transition

When connected to an atem 2m/e 4K chosing tools>ATEM>Trigger Auto>Transitions>DVE actualy switches the Sting for the transition.

Client v2.08 windows7/64
ATEM software V6.5

**Comment by Zebiolo** [comment]
Fixed in commit 5151217
