### ISSUE TITLE
Send Telnet command via Custom Command

### ISSUE THREAD

**Issue by Keksstar** [CasparCG/client#174]
Would be nice to have the ability to send out Telnet commands via "Custom Command" in the Client. (or with a new "Telnet" Tool)
A lot of devices in the broadcast world can understand Telnet commands. Would be great to have a way to control them via commands.

**Comment by mauricev78** [comment]
PLUS ONE

**Comment by aladinko** [comment]
Plus One

**Comment by dimitry-ishenko** [comment]
From what I understand Custom Commands are sent to the CasparCG server. We need Custom Shell Command for this. See issue #199.

**Comment by Julusian** [comment]
This is either a duplicate of #199, or can be handled by using some other software which this client talks to over http/osc
