### ISSUE TITLE
Minor things

### ISSUE THREAD

**Issue by mauricev78** [CasparCG/Client#176]
Hi there

Just a little list from our operators with minor things that would be nice :) to change / have

1. fallback to previous used folder in  save / open rundown dialogs.
2. transform widget larger maximum scale this is now 200% 
3. transform widget negative value's for scale to flip/mirror a image.
4. layer killer. for instane "ctrl-K" dialog which layer to kill enter.
5. a sort off jump to last 10second command for rehearsels
6. a "auto go to empty" option in a videolayer."LOADBG 1-10 EMPTY AUTO"

please let me know if i should post this as seperate Issues ??

regards
Maurice

**Comment by jesperstarkar** [comment]
5 and 6 are really really really needed for liveshows.

**Comment by hummelstrand** [comment]
Please file each bug/request as a separate issue, and then close this one. Thank you for your suggestions!

**Comment by mauricev78** [comment]
Closed on request

See issue 
#178 #179 #180 #181
