### ISSUE TITLE
Linux Client 2.0.8 CONSTANT delay

### ISSUE THREAD

**Issue by nephilime** [CasparCG/Client#185]
I found the problem in Linux Client version 2.0.8 - delay in all effects ( Transformation, Distort ... ) was not CONSTANT (+-5% of delay duration). It happens because QT (my version 5.4.2 (64 bit)) use default timer type (( Qt::CoarseTimer) - accuracy +-5% of desired interval). 

To fix this problem we have to use Qt::PreciseTimer type. 

Below you can find bash string to fix it in source from GitHub. You must execute it from Widgets folder before build.

grep -rl "this->executeTimer.setSingleShot(true);" ./ | xargs sed -i 's/this->executeTimer.setSingleShot(true);/this->executeTimer.setSingleShot(true);\nthis->executeTimer.setTimerType(Qt::PreciseTimer); /g'

**Comment by Zebiolo** [comment]
On 2015-11-13 12:14, nephilime wrote:
> [...] 
> To fix this problem we have to use Qt::PreciseTimer type. 

Please send a pull request against the next brannch.


	Peter

**Comment by dotarmin** [comment]
This is applicable on Windows and OS X as well.
