### ISSUE TITLE
Add support for Text producer 

### ISSUE THREAD

**Issue by deedos** [CasparCG/client#187]
Hi.  I have seen some text producer work on CasparCG Server (https://github.com/CasparCG/Server/tree/2.1.0/core/producer/text) and I 'm wondering if that feature will be available for the Client. That would be awesome.

thanks in advance

**Comment by Zebiolo** [comment]
On 2015-11-18 03:21, Daniel Roviriego wrote:
> I have seen some text producer work on CasparCG Server
> and I 'm wondering if that feature will be available
> for the Client.

Yes, that feature will be available in the future.
