### ISSUE TITLE
Client crashes when connected to ATEM with 6.6 firmware

### ISSUE THREAD

**Issue by TracyPeterson** [CasparCG/client#188]
Crashes when ATEM is added to settings.  Will not start if connected to ATEM.  Must disconnect to remove from settings

**Comment by hummelstrand** [comment]
Thank you for reporting, can you please provide more info, logs, a screen capture or anything else that helps the developers reproduce this error?

**Comment by TracyPeterson** [comment]
Reproduce by updating an atem to 6.6 then adding the atem IP address to settings.  Client will immediately crash and crash when you try to restart. I'll look for logs.

**Comment by hummelstrand** [comment]
@TracyPeterson Here's a few helpful hints at the kind of info that will help the developers reproduce and fix the error:

Please list as many details of your system, versions and what you are trying to do and how the bug manifests itself.

Here are some examples of the minimum amount of info we need:
Does it crash when you start it or after running for two weeks?
Do you get the same problem every time or only occasionally?
Has it just started give you problems after running smoothly for a year, or has it never worked?
Have you recently changed anything on the computer, such as changing anything about the hardware, installed a patch or new software or updated the OS?
What versions of the OS and all related software (Flash Player, CasparCG Server, CasparCG Client, Flash Professional, QuickTime etcetera) are you running?
What video cards and graphic cards are you using, including driver versions?
What exact error messages are you getting, and when are you getting them?

Please attach screenshots, screen capture videos, the files you are using, and more which show your problems and/or what you are trying to accomplish. Again; please provide the log file (found in the log folder configured in the casparcg.config settings file.)

Our mind-reading abilities are limited, so the more you can tell us, the greater the chance that someone will be able to help you!

**Comment by TracyPeterson** [comment]
There are no logs, becuase the client doesn't keep them.  

Windows 10 client.

Same problem every time, reproduce steps are above. 

It's just the client 2.8.  Probably the API implementation has changed.

Did you read my post and try the reproduction advice or just copy and paste that boiler text above?

**Comment by TracyPeterson** [comment]
http://www.atemuser.com/forums/atem-vision-mixers/developers/heads-66-official-sdk-will-break-your-code#new

**Comment by hummelstrand** [comment]
@tracypeterson
I did read your report, but since I am not the developer of CasparCG Client and don't have access to an ATEM, I can't either reproduce the error or do anything about it. I just wanted to help out by asking you to provide more info so that the main developer would have more to go on when prioritizing bugs and developing a fix. 
Again; thank you for reporting, and please continue to post helpful info on how to reproduce. For example, what version of CasparCG Client are you using?

**Comment by mauricev78** [comment]
hi 

maybe try the registry thing Zebilo was talking about in issue #155

grt

**Comment by TracyPeterson** [comment]
The problem isn't connectivity speed.  I did make this change, no change in behavior.  This crash occurs before rundown is loaded, when the hosts are connected in the client.  Please update your ATEM and test this on your client.  I believe it will be consistent.  Here is a writeup of changes made to ATEM SDK.  https://forum.blackmagicdesign.com/viewtopic.php?f=12&t=42142

Thanks.

**Comment by Julusian** [comment]
ATEM support is being remove in 2.3.0 of this client, to improve stability and minimise maintenance costs.
