### ISSUE TITLE
Client Crash when enabling remote trigger on HTTP related widgets

### ISSUE THREAD

**Issue by mauricev78** [CasparCG/Client#191]
Hi there all

on the following widgets 
HTMLpage
HTTPget
HTTPpost
the client crashes as soon as you enter a UID to remote trigger it

all other widgets i normally use don't crash but i did not test all off them :)
work around for now is too put them in a group

working with revision fdb9b34f2c
on a mac

grt
maurice

**Comment by Zebiolo** [comment]
Fixed in 4580d2f. Can you verify it's working before closing this issue.

**Comment by mauricev78** [comment]
Thanks Zebiolo

first tests shows good results
i will close this issue
