### ISSUE TITLE
Duration value cannot exceeds more then 5characters

### ISSUE THREAD

**Issue by Niwreg** [CasparCG/Client#194]
Hi,

I think the duration value bij output is not faulty

i try to add an logo overlay which shows 2 seconds after item start, and disapear 2 seconds before item end. So i group the items and try to set the logo duration in ms to the clip length but u cant use more then 99999ms 

Is this correct or i'm i doind something wrong?

**Comment by Zebiolo** [comment]
I have submitted a pull request #196

**Comment by dotarmin** [comment]
This is fixed by @Zebiolo and pull request #196. It is included in the next release of the client.
