### ISSUE TITLE
Rundown xml formatting

### ISSUE THREAD

**Issue by Julusian** [CasparCG/Client#216]
I am often finding myself storing rundown xml files in a git repo, along with the graphics they are designed for.
As the xml get saved as one line it gets detected by git as a binary file, and so it is not possible to view the contents or changes, whereas if the xml was formatted nicely then it would be easy to see the changes.

Doing this will also make it easier to make mass changes to the files in a text editor if required.

**Comment by 5opr4ni** [comment]
Hi Julusian

You can use Sublime Text to format your XML, the client can read formated XML. ;)
https://www.sublimetext.com/3
and use this plug in.
http://www.keyurraval.com/Blog/Formatting-XML-and-JSON-using-Sublime-Text

This is not an issue, and should be asked in the CasparCG Forums.

/Olle Soprani

**Comment by Julusian** [comment]
Hi Olle

I know I can format it elsewhere but it would still be nice to have the xml saved that way, otherwise it will require formatting it after saving to be able to track the changed in git.

**Comment by 5opr4ni** [comment]
Ok! We will take it up for discussion.

/Olle

**Comment by dotarmin** [comment]
Fixed, will be included in the next release of the CasparCG Client.
