### ISSUE TITLE
Next command and Trigger on Next feature

### ISSUE THREAD

**Issue by dimitry-ishenko** [CasparCG/Client#223]
Could someone please give me an example of when and how these are used? I haven't been able to figure it out. Thank you.

**Comment by 5opr4ni** [comment]
Hi Dimitry

Trigger on Next is a vital option that are used frequently by us, thats why we have it. ;)
It makes it possible to execute a Group in two steps. Imagine that you have one image and one transform, and that you want to show the image as it is first, and later in time, want to transform to a new scale and position on command from the "Producer (person)", then you can hold the transform by adding a trigger on next on it. When the command arrives from the "Producer (person)" you press Next (F5) and the transform is executed. In this way we reduce the amount of items in the rundown by grouping. (The next command is triggered on the group)  We use groups a lot in our rundowns. I thing there is some commands in the toolbox that misses the possibility, so it would be something to add.

Keep up the god work Dimitry
/Olle Soprani
Founder of CasparCG

**Comment by dimitry-ishenko** [comment]
Hi Olle, thank you very much. I think it makes sense now. I will play around with it later to make sure I fully understand it.
And thank you for creating this great product!
