### ISSUE TITLE
Aux buses on ATEM mixers. 

### ISSUE THREAD

**Issue by 5opr4ni** [CasparCG/client#229]
Aux buses at listed as sources in the client. They should be a destination in Input source.

**Comment by dotarmin** [comment]
Did you use firmware 6.9 of the ATEM switcher?

/Armin

**Comment by 5opr4ni** [comment]
Yes!

**Comment by Julusian** [comment]
ATEM support is being remove in 2.3.0 of this client, so this no longer applies
