### ISSUE TITLE
matrix control

### ISSUE THREAD

**Issue by daenix** [CasparCG/client#237]
<feature enhancement>
It would be great if CasparCG client would be able to control Blackmagic Videohub (or a Leitch matrix. )
However the client should have some restriction on accessing certain sources and destinations not to interfere to the whole matrix but at least to the few destinations. It would be nice to pull the in/out mnemonics from matrix.  Thank You

**Comment by Julusian** [comment]
We are scoping the client down to not support controlling other devices, and only supporting casparcg and some generic protocols (http, osc etc).
You can achieve this kind of control by using one of these generic protocols to some other software which can talk to a matrix
