### ISSUE TITLE
 Virus in dev. build of the newest client?

### ISSUE THREAD

**Issue by dotarmin** [CasparCG/Client#239]
> @didikunz wrote:
>Hi
>my Kaspersky deleted imediately caspar.dll after unzipping the newest dev. build of the Client.
>CasparCG Client 012c50b49a48f4f2bc8dbbde1090ebe9436be814
>
>Object name: HEUR:Trojan.Win32.Generic Object type: Trojan program
>
>same experiences?
>
> (posted
 >by Peter Aellig in the forum)

**Comment by dotarmin** [comment]
I have checked into this again and I can't find anything strange. 
The latest commit (012c50b) in the master branch that was built for Windows was built because a member reported that build for Windows was missing which was right, the automated build triggering did not fire as expected and was done by me manually.

I have looked into this as said with various tools and no reports of something suspect. I will leave this issue open for a couple of days to see if more members can confirm this as well. 

/Armin

**Comment by hreinnbeck** [comment]
---------- Forwarded message ----------
From: <newvirus@kaspersky.com>
Date: Tue, Nov 14, 2017 at 10:06 AM
Subject: RE: Anti-virus Lab replies to your request [VD3][FILE:2][LN:en] [KLAN-7144084609]
To: phillipseamore@gmail.com


Hello,

Sorry, it was a false detection. It will be fixed.
Thank you for your help.

Sincerely yours,
Igor Loshchakov, Malware Analyst, Kaspersky Lab

39A/3 Leningradskoe Shosse, Moscow, 125212, Russia  Tel./Fax: + 7 (495) 797 8700  http://www.kaspersky.com https://securelist.com

**Comment by dotarmin** [comment]
@hreinnbeck Thanks!
