### ISSUE TITLE
Open Recent Rundown

### ISSUE THREAD

**Issue by didikunz** [CasparCG/client#246]
Why can this list become full? Instead it should remove the entry, that has been not open the longest, as any other applications do.

**Comment by dimitry-ishenko** [comment]
@didikunz Rescent -> Recent

**Comment by didikunz** [comment]
...or whatever it‘s called. Do you at least understand what I am talking about?

**Comment by dimitry-ishenko** [comment]
I do. This it totally broken in the Client. I was trying to say that you've misspelled the word "recent".

**Comment by dotarmin** [comment]
> Do you at least understand what I am talking about?

Yes we do. 

> This it totally broken in the Client
I agree, it doesn't work that good for the moment.
