### ISSUE TITLE
 CasparCG Client 2.2.0 RC1 build for Mac OS

### ISSUE THREAD

**Issue by grahamspr86** [CasparCG/client#279]
Any chance of a build of the  CasparCG Client 2.2.0 RC1 for Mac OS?

**Comment by hreinnbeck** [comment]
http://builds.casparcg.com/CasparCG%20Client/next/

**Comment by grahamspr86** [comment]
That's not the RC1 Build. The build for RC1 has only been done for Windows!

**Comment by hreinnbeck** [comment]
The only thing missing from that build are the two latest commits here (the ones never than 3dad82f):
https://github.com/CasparCG/client/commits/next

Update build script for Qt5.4 …
Update libqatemcontrol …

**Comment by grahamspr86** [comment]
I'm having an issue with the previous build and an ATEM where the client crashes I see there is a change which I'm hoping resolves it. I see from the comments of the ATEM fix that the library still needs to be compiled for Mac

**Comment by Julusian** [comment]
There is a build available https://github.com/CasparCG/client/releases/tag/v2.2.0-rc2
Automated builds with github actions have been setup, so this should not happen going forward
