### ISSUE TITLE
Error Building Project

### ISSUE THREAD

**Issue by vishalnischal2011** [CasparCG/client#291]
When i am building project. i am getting following error.

![image](https://user-images.githubusercontent.com/69953126/98240015-d38d4500-1f8e-11eb-8285-2933437241f8.png)

Please help in resolving.

**Comment by Julusian** [comment]
Are you building on/for 32bit windows? The client only supports 64bit

**Comment by vishalnischal2011** [comment]
Dear julusian,

I am building project on my 64 bit windows 10 OS machine.

**Comment by Julusian** [comment]
The build process has been reworked, this should no longer be an issue
