### ISSUE TITLE
Client 2.2.0 crashes when connecting to ATEM Constellation switcher

### ISSUE THREAD

**Issue by sarksim** [CasparCG/client#299]
When I try to connect to out ATEM Constellation switcher via the client interface and click on "test connection" the client just shuts down. If I actually add the mixer to the list the client also shuts down and refuses to open until I disconnect ATEM from the network. Running software version 8.1.2 on the ATEM Constellation, also tested on 8.0.

Our other ATEM works fine (2M/E Production Studio w/ software version 7.2)

**Comment by 7sorkr** [comment]
> When I try to connect to out ATEM Constellation switcher via the client interface and click on "test connection" the client just shuts down. If I actually add the mixer to the list the client also shuts down and refuses to open until I disconnect ATEM from the network. Running software version 8.1.2 on the ATEM Constellation, also tested on 8.0.
> 
> Our other ATEM works fine (2M/E Production Studio w/ software version 7.2)

I've been connected with the CasparCG Client version as a lower version. Not everything can be implemented.

**Comment by Julusian** [comment]
ATEM support is being remove in 2.3.0 of this client, to improve stability and minimise maintenance costs.

**Comment by daenix** [comment]
Please tell us where is release 2.3.0  
I didnt find it here: https://github.com/CasparCG/client/releases/

**Comment by Julusian** [comment]
Its not finished yet, but you can download the in-progress builds from https://casparcg.com/builds/CasparCG%20Client/main/
the macos-arm64 build doesnt run currerntly, Im not aware of any other new issues

**Comment by 7sorkr** [comment]
CasparCG Client Version connected to Constellation 8K 

INPUT (O)
AUDIO (X)
MACRO (O)
......

https://casparcg.com/builds/CasparCG%20Client/next/CasparCG%20Client%203dad82ffaf7b097b40d91095c87ca0f4e7c367ee.zip (Constellation 8K connect)
https://casparcg.com/builds/CasparCG%20Client/next/
![client](https://github.com/CasparCG/client/assets/32606306/ce15a89e-5ed6-40e2-adf7-d3d6a69c7cff)
