### ISSUE TITLE
Playout Command Pause or Resume does not operate

### ISSUE THREAD

**Issue by amwtech** [CasparCG/client#301]
The text in the Playout Command Inspector drop down is compared with the list of commands held in src/Common/Playout.cpp. The dropdown text does not match the reference text in Playout.cpp lines 16 and 49. The reference text is "Pause / Resume" but the dropdown text is "Pause".

Editing line 48 of src/Widgets/Inspector/InspectorPlayoutCommandWidget.ui from `<string>Pause</string>` to `<string>Pause / Resume</string>` and rebuilding the client corrects the error.

**Comment by Julusian** [comment]
Fix applied in https://github.com/CasparCG/client/commit/67a5c58b60237534f89b9d460e48e3cca3afc7d0
I havent tested it, hopefully it still works

**Comment by amwtech** [comment]
Tested on Mac and Windows client build. Operates correctly.
