### ISSUE TITLE
Compilation make error with CasparCG-client

### ISSUE THREAD

**Issue by mks75** [CasparCG/client#302]
Hi, I am trying to compile and install the latest code of CasparCG Client, but getting make errors. I have tried on both Ubuntu 18.04 and Ubuntu 22.04 OS but the error is same. Any advice please?

testadmin@svr041:~/Downloads/client-next/build-scripts$ ./set-variables-and-build-linux.sh 
Cleaning...
Running qmake...
Info: creating stash file /home/testadmin/Downloads/client-next/build/.qmake.stash
Reading /home/testadmin/Downloads/client-next/src/Common/Common.pro [/home/testadmin/Downloads/client-next/build/Common]
sh: 1: git: not found
sh: 1: git: not found
Reading /home/testadmin/Downloads/client-next/src/Atem/Atem.pro [/home/testadmin/Downloads/client-next/build/Atem]
Reading /home/testadmin/Downloads/client-next/src/Caspar/Caspar.pro [/home/testadmin/Downloads/client-next/build/Caspar]
Reading /home/testadmin/Downloads/client-next/src/TriCaster/TriCaster.pro [/home/testadmin/Downloads/client-next/build/TriCaster]
Reading /home/testadmin/Downloads/client-next/src/Panasonic/Panasonic.pro [/home/testadmin/Downloads/client-next/build/Panasonic]
Reading /home/testadmin/Downloads/client-next/src/Sony/Sony.pro [/home/testadmin/Downloads/client-next/build/Sony]
Reading /home/testadmin/Downloads/client-next/src/Spyder/Spyder.pro [/home/testadmin/Downloads/client-next/build/Spyder]
Reading /home/testadmin/Downloads/client-next/src/Web/Web.pro [/home/testadmin/Downloads/client-next/build/Web]
Reading /home/testadmin/Downloads/client-next/src/Gpi/Gpi.pro [/home/testadmin/Downloads/client-next/build/Gpi]
Reading /home/testadmin/Downloads/client-next/src/Osc/Osc.pro [/home/testadmin/Downloads/client-next/build/Osc]
Reading /home/testadmin/Downloads/client-next/src/Repository/Repository.pro [/home/testadmin/Downloads/client-next/build/Repository]
Reading /home/testadmin/Downloads/client-next/src/Core/Core.pro [/home/testadmin/Downloads/client-next/build/Core]
Reading /home/testadmin/Downloads/client-next/src/Widgets/Widgets.pro [/home/testadmin/Downloads/client-next/build/Widgets]
Reading /home/testadmin/Downloads/client-next/src/Shell/Shell.pro [/home/testadmin/Downloads/client-next/build/Shell]
Building...
cd Common/ && ( test -e Makefile || /home/testadmin/Qt5.14.2/5.14.2/gcc_64/bin/qmake -o Makefile /home/testadmin/Downloads/client-next/src/Common/Common.pro -spec linux-g++-64 CONFIG+=release ) && make -j8 -f Makefile 
make[1]: Entering directory '/home/testadmin/Downloads/client-next/build/Common'
g++ -c -m64 -pipe -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DCOMMON_LIBRARY -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I../../src/Common -I. -I../../../../Qt5.14.2/5.14.2/gcc_64/include -I../../../../Qt5.14.2/5.14.2/gcc_64/include/QtGui -I../../../../Qt5.14.2/5.14.2/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I../../../../Qt5.14.2/5.14.2/gcc_64/mkspecs/linux-g++-64 -o Timecode.o ../../src/Common/Timecode.cpp
g++ -c -m64 -pipe -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DCOMMON_LIBRARY -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I../../src/Common -I. -I../../../../Qt5.14.2/5.14.2/gcc_64/include -I../../../../Qt5.14.2/5.14.2/gcc_64/include/QtGui -I../../../../Qt5.14.2/5.14.2/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I../../../../Qt5.14.2/5.14.2/gcc_64/mkspecs/linux-g++-64 -o Xml.o ../../src/Common/Xml.cpp
g++ -c -m64 -pipe -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC -DCOMMON_LIBRARY -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I../../src/Common -I. -I../../../../Qt5.14.2/5.14.2/gcc_64/include -I../../../../Qt5.14.2/5.14.2/gcc_64/include/QtGui -I../../../../Qt5.14.2/5.14.2/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I../../../../Qt5.14.2/5.14.2/gcc_64/mkspecs/linux-g++-64 -o Playout.o ../../src/Common/Playout.cpp
rm -f libcommon.so.1.0.0 libcommon.so libcommon.so.1 libcommon.so.1.0
g++ -m64 -Wl,-O1 -Wl,-rpath,/home/testadmin/Qt5.14.2/5.14.2/gcc_64/lib -shared -Wl,-soname,libcommon.so.1 -o libcommon.so.1.0.0 Timecode.o Xml.o Playout.o  -L/usr/X11R6/lib64 /home/testadmin/Qt5.14.2/5.14.2/gcc_64/lib/libQt5Gui.so /home/testadmin/Qt5.14.2/5.14.2/gcc_64/lib/libQt5Core.so -lGL -lpthread    
/usr/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status
Makefile:291: recipe for target 'libcommon.so.1.0.0' failed
make[1]: *** [libcommon.so.1.0.0] Error 1
make[1]: Leaving directory '/home/testadmin/Downloads/client-next/build/Common'
Makefile:59: recipe for target 'sub-Common-make_first' failed
make: *** [sub-Common-make_first] Error 2
Command exited with non-zero status 2
Build time 0:01.16
make failed

**Comment by PistonPL** [comment]
Possible solution
https://stackoverflow.com/questions/18406369/qt-cant-find-lgl-error

**Comment by mks75** [comment]
Thanks, I tried and the make proceeds but now getting the following error. Any advice please?

collect2: error: ld returned 1 exit status
Makefile:282: recipe for target 'shell' failed
make[1]: *** [shell] Error 1
make[1]: Leaving directory '/home/testadmin/Downloads/client-next/build/Shell'
Makefile:412: recipe for target 'sub-Shell-make_first' failed
make: *** [sub-Shell-make_first] Error 2
Command exited with non-zero status 2
Build time 11:48.07
make failed

**Comment by PistonPL** [comment]
It can be caused by many things.  Still you are circling around Qt library. Missing dependences?

**Comment by Julusian** [comment]
The build process has been reworked so this no longer applies
