### ISSUE TITLE
CasparCG client is not build for Windows 10 x64 With Qt 5.14.2 neither MingW 7.3.0 x64 nor MSVC 2017(15.9.3)

### ISSUE THREAD

**Issue by RomanED** [CasparCG/client#303]
Qt 5.14.2 with MingW 7.3.0 or MSVC 2017(15.9.x) 64 bit:

undefined reference to gpio::serial_port_device::create

what versions of dependencies(Qt version, msvc version compiler and other) do I need for a successful build?

Qt 6.4 with MSVC 2019 (17.3) many errors with qt and others...

**Comment by RomanED** [comment]
LNK1104: cannot open file 'qatemcontrol.lib'

 LNK1104: cannot open file 'boost_date_time-mgw49-mt-1_57.lib'

LNK1104: cannot open file 'boost_date_time-mgw49-mt-1_57.lib'

**Comment by dimitry-ishenko** [comment]
FWIW, you can grab the gpio lib from here:

https://github.com/CasparCG/Tools/tree/master/cpp/gpio/trunk

**Comment by RomanED** [comment]
I tried build CasparCG client with MingW 7.3.0 x64 , add executable and builded libs in deploy directory, and every time I get a runtime error "The entry point <..name_entry> to the procedure was not found"

**Comment by RomanED** [comment]
Alarm, guys, i need your  help with Caspar Client?

**Comment by dimitry-ishenko** [comment]
@RomanED do you have to run in on Windows? If you can use Linux, I might be able to help you

**Comment by Julusian** [comment]
The build process has been reworked so this no longer applies
