### ISSUE TITLE
Video countdown dosen't work in Client v3.2.0 

### ISSUE THREAD

**Issue by lassewamsler** [CasparCG/client#312]
Hi :)

I have updated my CasparCG applications, but after the update, the countdown ("count video progress down") dosen't work in the client. Why?

I am using:
Scanner v1.3.4 (on Windows 11 Pro)
Server v2.4.0 (on Windows 11 Pro)
Client v2.3.0 (on Windows 11 Pro)

Do someone have the same issue?

**Comment by Julusian** [comment]
This is a known issue that has been fixed since the RC release of the client. It will be included in the next release
