### ISSUE TITLE
Out Transition option

### ISSUE THREAD

**Issue by piotrszmidt** [CasparCG/Client#40]
As for now, ther is only option for "in transition" for item on run down. If its possible to set "out transition" it will make it much easier in some cases.

**Comment by dimitry-ishenko** [comment]
Two years later... :) FYI, you can simulate this behaviour with Custom Command.  Put your video and Custom command into the same group. In the Custom Command enter this under Play option: loadbg 1-10 empty auto mix 10. The video will play and fade out at the end. Change your channel/layer and transition/time for desired OUT transition.

**Comment by jesperstarkar** [comment]
There's an item called "Fade to black", which is going to be called "Fade out" in the next version.

**Comment by dimitry-ishenko** [comment]
@jesperstarkar, I gave "bad" example with fade out transition, and you correct, in this particular case FTB is a better choice (with Use Auto enabled).
But the OP had asked about "out transitions" and for anything other than FTB, Custom Command is the way to go

**Comment by dotarmin** [comment]
Already implemented.
