### ISSUE TITLE
Change f0/f1/f2f/3/etc. fields back to 2.0.1 version?

### ISSUE THREAD

**Issue by ghost** [CasparCG/Client#73]
Hey all,

In the new client version every time I want to change a 'f-field' I have to do it in a popup, like this http://puu.sh/4tKjY. It really hurts my fast workflow, as I like to use TAB to quickly switch between fields.

Is there an option to change it back like this, as in 2.0.1: http://puu.sh/4tKn4

Thanks!

**Comment by dotarmin** [comment]
This issue won't be fixed because the new work flow has been hanging around for a while and no comments has been added for a couple of years now.
