### ISSUE TITLE
Enhancement: Field for entering Stored Dataset name

### ISSUE THREAD

**Issue by jesperstarkar** [CasparCG/Client#98]
When using Stored Datasets, you shouldn't enter the name of the set in the "value"-coloumn and (in most cases) end up with "f0" as "Name" parameter. This makes no sense, and clutters up the impression of the (allready cluttered) component system.

It would be easier to understand stored data if you entered the name in another field, separate from regular data.

**Comment by dotarmin** [comment]
Check issue #161 instead.
